# in .cargo/config.toml

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

# https://os.phil-opp.com/minimal-rust-kernel/
[unstable]
# memset functions (rust version tried and tested) (normally links to C lib)
# Therefore disabled by default
build-std-features = ["compiler-builtins-mem"]
# Makes cargo recompile the core library (which is precompiled on other target systems)
build-std = ["core", "compiler_builtins"]

# Set default target
[build]
target = "x86_64-ruffyos.json"

# To use the booimage's run functionality
# Uses qemu to run the os
# command used: qemu-system-x86_64 -drive format=raw,file=target/x86_64-ruffyos/debug/bootimage-ruffyos.bin
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
